ciテスト実施23

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,15 +20,15 @@ jobs:
       - run:
           command: npm run dev
           working_directory: src
-      - run:
-          name: Wait for MySQL to be ready
-          command: |
-            for i in `seq 1 60`; do
-              nc -z mysql 3306 && echo Success && exit 0
-              echo -n .
-              sleep 2
-            done
-            echo "MySQL failed to start" && exit 1
+      # - run:
+      #     name: Wait for MySQL to be ready
+      #     command: |
+      #       for i in `seq 1 60`; do
+      #         nc -z mysql 3306 && echo Success && exit 0
+      #         echo -n .
+      #         sleep 2
+      #       done
+      #       echo "MySQL failed to start" && exit 1
       - run:
           name: php test
           command: |
